# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4GVt7VTNBwBkdeosjp3v0_hwJcFEoul
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Завантаження даних
data = pd.read_csv('data_multivar_nb.txt', header=None)  # Необхідно вказати, чи є заголовки
data.columns = [f'feature_{i}' for i in range(data.shape[1]-1)] + ['label']  # Додавання назв колонок
print("Дані завантажено:", data.head())

# 2. Визначення ознак і міток
X = data.drop(columns=['label'])
y = data['label']

# 3. Розділення даних на навчальну та тестову вибірки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Навчання моделі SVM
svm_model = SVC(kernel='linear')  # Ви можете змінити ядро
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

# 5. Навчання наївного байєсівського класифікатора
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)

# 6. Оцінка якості моделей
print("\nРезультати Support Vector Machine:")
print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))
print(f"Accuracy (SVM): {accuracy_score(y_test, y_pred_svm):.3f}")

print("\nРезультати Naive Bayes:")
print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))
print(f"Accuracy (Naive Bayes): {accuracy_score(y_test, y_pred_nb):.3f}")

# Висновки
if accuracy_score(y_test, y_pred_svm) > accuracy_score(y_test, y_pred_nb):
    print("\nВисновок: Модель SVM краще класифікує дані.")
else:
    print("\nВисновок: Модель наївного байєса краще класифікує дані.")